# Fractal Explorer: Visualizing the Mandelbrot Set

# Learning Objective:
# This tutorial will introduce you to the fascinating world of fractals by
# teaching you how to visualize and zoom into the Mandelbrot set using Python.
# We will learn about:
# 1. Basic complex number arithmetic for fractal generation.
# 2. Iterative functions and their escape-time algorithms.
# 3. Mapping mathematical coordinates to image pixels.
# 4. Using the Pillow library for image manipulation.

# Import necessary libraries
# Pillow (PIL fork) is used for image creation and manipulation.
# If you don't have it installed, run: pip install Pillow
from PIL import Image

# --- Configuration ---
# Image dimensions: Width and height of the output image in pixels.
WIDTH = 800
HEIGHT = 600

# --- Mandelbrot Set Generation Function ---
# This function calculates the "color" of a pixel based on how quickly
# a point in the complex plane escapes a certain boundary when iterated.
def mandelbrot(c, max_iterations):
    # `c` is a complex number representing a point in the complex plane.
    # `max_iterations` is the maximum number of times we will iterate the function.

    # We start with z = 0. This is the initial value for our iteration.
    z = 0j # 'j' denotes the imaginary unit in Python, so 0j is 0 + 0i

    # We iterate the function z = z*z + c.
    # The Mandelbrot set is defined by the condition that the sequence
    # generated by this iteration remains bounded (doesn't go to infinity).
    for i in range(max_iterations):
        # Check if the magnitude of z exceeds 2.
        # If |z| > 2, the sequence will diverge to infinity.
        # Squaring |z| is computationally cheaper than taking the square root.
        if abs(z) > 2:
            # If it escapes, return the number of iterations it took.
            # This value will determine the color of the pixel.
            return i
        # Perform the core Mandelbrot iteration: z = z^2 + c
        z = z*z + c
    # If the loop finishes without escaping, it means the point `c` is
    # likely within the Mandelbrot set. We return `max_iterations` to
    # indicate it's part of the set (or takes a long time to escape).
    return max_iterations

# --- Image Generation Function ---
# This function creates the fractal image by iterating through each pixel,
# mapping it to a complex number, and then calling `mandelbrot` to determine its color.
def generate_fractal_image(center_x, center_y, zoom, max_iterations):
    # `center_x`, `center_y`: The real and imaginary parts of the center of our view
    # `zoom`: Controls how zoomed in we are. Higher values mean more zoom.
    # `max_iterations`: The maximum number of iterations for the mandelbrot function.

    # Create a new blank image with the specified width and height, in RGB mode.
    # 'RGB' means each pixel will have a Red, Green, and Blue component.
    img = Image.new('RGB', (WIDTH, HEIGHT), (0, 0, 0))
    # `pixels` gives us access to modify individual pixels.
    pixels = img.load()

    # Calculate the range of the complex plane we are viewing.
    # `scale` determines how much of the complex plane is mapped to our image width.
    # A larger `zoom` means a smaller `scale`, effectively zooming in.
    scale = 3.0 / (zoom * HEIGHT) # Adjust scale based on zoom and height

    # Iterate through each pixel in the image.
    for x in range(WIDTH):
        for y in range(HEIGHT):
            # Map the pixel coordinates (x, y) to a complex number `c`.
            # We need to translate pixel coordinates (0 to WIDTH, 0 to HEIGHT)
            # to complex plane coordinates relative to our `center_x` and `center_y`.
            # The `scale` factor adjusts for the zoom level.
            # `(x - WIDTH / 2)`: Centers the pixel coordinates around the image center.
            # `scale * (y - HEIGHT / 2)`: Similarly for the imaginary part.
            real = center_x + (x - WIDTH / 2) * scale
            imag = center_y + (y - HEIGHT / 2) * scale
            c = complex(real, imag)

            # Get the number of iterations for this complex number `c`.
            iterations = mandelbrot(c, max_iterations)

            # Determine the color of the pixel based on `iterations`.
            # If `iterations` is `max_iterations`, the point is in the set.
            # We color these points black.
            if iterations == max_iterations:
                color = (0, 0, 0) # Black
            else:
                # For points outside the set, we use `iterations` to create a color.
                # This is a simple coloring scheme. More complex schemes can create
                # more visually appealing fractals.
                # We use the modulo operator (%) to wrap the iteration count,
                # ensuring we cycle through colors.
                # The formula `(iterations % 256)` maps the iteration count to a value
                # between 0 and 255, which is suitable for RGB color components.
                color_val = iterations % 256
                # Create an RGB tuple. Here, we're making a gradient based on the iteration count.
                color = (color_val, color_val // 2, color_val) # Example: Shades of blue/green

            # Set the pixel color.
            pixels[x, y] = color

    # Return the generated image object.
    return img

# --- Example Usage ---
if __name__ == "__main__":
    # --- Default View ---
    # This is a common view of the Mandelbrot set.
    # `center_x`: Real part of the center (e.g., -0.75 for standard view).
    # `center_y`: Imaginary part of the center (e.g., 0.0 for standard view).
    # `zoom`: How zoomed in we are. 1.0 is a good starting point for a full view.
    # `max_iterations`: Higher values give more detail but take longer to compute.
    center_real = -0.75
    center_imag = 0.0
    zoom_level = 1.0
    iterations = 100

    print(f"Generating initial fractal image with center=({center_real}, {center_imag}), zoom={zoom_level}, iterations={iterations}...")
    fractal_image = generate_fractal_image(center_real, center_imag, zoom_level, iterations)
    # Save the image to a file.
    fractal_image.save("mandelbrot_initial.png")
    print("Initial image saved as mandelbrot_initial.png")

    # --- Zoomed-In View Example ---
    # Let's zoom into a specific region.
    # This region is known for its intricate spiral patterns.
    # We adjust the center and increase the zoom level.
    print("\nGenerating zoomed-in image...")
    zoom_center_real = -0.743643887075
    zoom_center_imag = 0.131825904205
    zoom_level_zoomed = 1000.0 # Significantly increased zoom
    iterations_zoomed = 500 # More iterations for higher zoom for detail

    zoomed_fractal_image = generate_fractal_image(zoom_center_real, zoom_center_imag, zoom_level_zoomed, iterations_zoomed)
    zoomed_fractal_image.save("mandelbrot_zoomed.png")
    print(f"Zoomed image saved as mandelbrot_zoomed.png (center=({zoom_center_real}, {zoom_center_imag}), zoom={zoom_level_zoomed})")

    # You can now open 'mandelbrot_initial.png' and 'mandelbrot_zoomed.png'
    # in an image viewer to see the beautiful fractal patterns.
    # Experiment with different `center_real`, `center_imag`, `zoom_level`,
    # and `max_iterations` values to explore other parts of the Mandelbrot set!